# Generated by Django 5.1.4 on 2024-12-20 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_profile_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='division',
            field=models.CharField(default='A', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='full_name',
            field=models.CharField(default='Full Name', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='roll_no',
            field=models.CharField(default='Roll No', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='std',
            field=models.CharField(default='std', max_length=20),
        ),
    ]
