# Generated by Django 5.1.4 on 2024-12-22 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_attendance_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Name of the Course', max_length=200)),
                ('description', models.TextField()),
            ],
        ),
    ]
